language: R
sudo: required
cache: packages

r:
  - release
  - devel
  - oldrel
  - 3.5
  - 3.4

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: change
